dist: trusty
sudo: required
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - cmake
      - build-essential
      - libssl-dev
      - libcurl4-openssl-dev
      - libjansson-dev
      - libgmp-dev
      - automake
      - libgmp-dev

script:
  - ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
  - ln -s /usr/bin/g++-7 /usr/local/bin/g++
  - export CC=/usr/bin/gcc-7
  - export CXX=/usr/bin/g++-7
  - make test
